theme: minima
title: Rust Verification Tools
author: Google Research
baseurl: "/rust-verification-tools"
gitrepo: https://github.com/project-oak/rust-verification-tools/

header_pages:
  - about.md
  - tools.md
  - Documentation.md
  - installation.md

